// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfAMynyv6vxoloUXYtNU6TRMSC9fg310k',
    appId: '1:1036083075628:web:62dce3fb3b204ea757cf89',
    messagingSenderId: '1036083075628',
    projectId: 'mynotes-flutter-aryan',
    authDomain: 'mynotes-flutter-aryan.firebaseapp.com',
    storageBucket: 'mynotes-flutter-aryan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCN9VRhd4N6TeFMgWkPY5PwAz_YMzP5X0',
    appId: '1:1036083075628:android:54e049d18818aa2d57cf89',
    messagingSenderId: '1036083075628',
    projectId: 'mynotes-flutter-aryan',
    storageBucket: 'mynotes-flutter-aryan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnKXF89OFJX8KYby_d30d5NeuW8GHPz-Y',
    appId: '1:1036083075628:ios:e6a2cb6bbd5d487c57cf89',
    messagingSenderId: '1036083075628',
    projectId: 'mynotes-flutter-aryan',
    storageBucket: 'mynotes-flutter-aryan.appspot.com',
    iosClientId: '1036083075628-isagor5rcdnvato27paqnuerivbc6da9.apps.googleusercontent.com',
    iosBundleId: 'com.aryan2.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnKXF89OFJX8KYby_d30d5NeuW8GHPz-Y',
    appId: '1:1036083075628:ios:190c8e4dc798c72857cf89',
    messagingSenderId: '1036083075628',
    projectId: 'mynotes-flutter-aryan',
    storageBucket: 'mynotes-flutter-aryan.appspot.com',
    iosClientId: '1036083075628-abhfrloou46pobqbihr3e78t0jl2ikso.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
